os: linux
dist: focal
sudo: true

language:
  - cpp

addons:
  apt:
    packages:
      - libgtest-dev
      - cmake
      - lcov

install:
  - pip install --user cpp-coveralls

script:
  - echo "Installing Google Test Framework"
  - pushd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp ./lib/libgtest*.a /usr/lib
  - popd
  - echo "Building & Running Sample Applications"
  - mkdir build && cd build
  - cmake ../ -DBUILD_EXAMPLES=ON
  - cmake --build .
  - examples/DDSketch_Examples
  - cd .. && rm -rf build
  - echo "Running Unit Tests and checking coverage"
  - mkdir build && cd build
  - cmake ../ -DRUN_COVERAGE=ON
  - cmake --build .
  - tests/DDSketch_Unit_Tests
  - cd ..
  - echo "Done"

after_success:
  # Collect coverage and push to coveralls.info
  # Ignore third party source code and tests
  - if [ "${CC}" = "gcc" ]; then
        find build/
        \(
            -name '*.gcda' -or
            -name '*.gcno' -or
            -name 'DDSketch_Unit_Tests'
        \)
            -exec cp {} tests/ \; ;
        rm -rf build;
        cd tests;
        coveralls
            --root ../
            --build-root ./
            --exclude lib
            --gcov-options '\--long-file-names --preserve-paths';
    fi

notifications:
  email: false
